### ISSUE TITLE
Understanding justification of using SNN over KNN

### ISSUE THREAD

**Issue by newtonharry** [RoseYuan/sc_chromatin_benchmark#2]
Hi,

I'm still relatively new to this area as well as machine learning. Could  you please explain why you chose SNN over KNN? I can see in snapatac2 that it utilises KNN without considering the "shared" aspect of the graph. Did using this "shared" property of the graph have a unique relationship  to the use of the metrics in a way a kNN graph can't?

**Comment by RoseYuan** [comment]
Hi @newtonharry,
Here are some reference for this topic:
1. http://mlwiki.org/index.php/SNN_Clustering
2. Xu, Chen, and Zhengchang Su. "Identification of cell types from single-cell transcriptomes using a novel clustering method." Bioinformatics 31.12 (2015): 1974-1980 https://doi.org/10.1093/bioinformatics/btv088.

Basically, SNN is considered more robust to noise when the data contain clustering structures with varying density.
